### PR TITLE
Add more asset links

### LINKED ISSUE #5: Any plans to include metadata URLs alongside the visual.tif URLs?
Maxar's ARD deliverables can contain ~17 metadata files for any given visual.tif https://ard.maxar.com/docs/getting-started/about-sample-data-001/

```
📁 {bucket) maxar-data-samples
└── 📁 {prefix} sample-001
    └── 📁 {UTM-zone} 10
        └── 📁 {quadkey} 120020223032
            └── 📁 {date of acquisition} 2016-10-08
            └─╴📄 103001005D31F500-cloud-mask.gpkg
            └─╴📄 103001005D31F500-cloud-shadow-mask.gpkg
            └─╴📄 103001005D31F500-clouds.tif
            └─╴📄 103001005D31F500-data-mask.gpkg
            └─╴📄 103001005D31F500-healthy-vegetation.tif
            └─╴📄 103001005D31F500-healthy-vegetation-mask.gpkg
            └─╴📄 103001005D31F500-pan-flare.tif
            └─╴📄 103001005D31F500-pan-flare-mask.tif
            └─╴📄 103001005D31F500-ms-saturation-mask.gpkg
            └─╴📄 1103001005D31F500-ms-saturation.tif
            └─╴📄 103001005D31F500-ms.tif
            └─╴📄 103001005D31F500-pan.tif
            └─╴📄 103001005D31F500-terrain-shadow-mask.gpkg
            └─╴📄 103001005D31F500-terrain-shadows.tif
            └─╴📄 103001005D31F500-visual.tif
            └─╴📄 103001005D31F500-water-mask.gpkg
            └─╴📄 103001005D31F500-water.tif
            └─╴📄 103001005D31F500.json
```

I tested some URLs and they do look to occasionally be accessible for some of the datasets linked to in this project.

```bash
$ for FILENAME in 10300100DE4D9300-cloud-mask.gpkg \
                  10300100DE4D9300-cloud-shadow-mask.gpkg \
                  10300100DE4D9300-clouds.tif \
                  10300100DE4D9300-data-mask.gpkg \
                  10300100DE4D9300-healthy-vegetation.tif \
                  10300100DE4D9300-healthy-vegetation-mask.gpkg \
                  10300100DE4D9300-pan-flare.tif \
                  10300100DE4D9300-pan-flare-mask.tif \
                  10300100DE4D9300-ms-saturation-mask.gpkg \
                  10300100DE4D9300-ms.tif \
                  10300100DE4D9300-pan.tif \
                  10300100DE4D9300.json; do
      RESP=`curl -Is https://maxar-opendata.s3.amazonaws.com/events/New-Zealand-Flooding23/ard/60/213311212310/2022-12-11/$FILENAME | head -n1`
      if [[ $RESP == *"HTTP/1.1 200 OK"* ]]; then
          echo $FILENAME
      fi
  done
```

```
10300100DE4D9300-data-mask.gpkg
10300100DE4D9300-ms.tif
10300100DE4D9300-pan.tif
10300100DE4D9300.json
```

Any plans to name these URLs specifically within the GeoJSON manifest files?

### PR DESCRIPTION
**Pull request by giswqs**
Add more asset links in the GeoJSON file, including `"visual", "ms_analytic", "pan_analytic", "data-mask"`. 

Fix #5

### CODE REVIEW

**Comment by marklit** [comment]
Will all the .geojson files in the `datasets/` folder be refreshed with these fields as well?

**Comment by giswqs** [comment]
It has been running several hours now. Building virtual mosaics is very slow. I should be available tomorrow morning. 

image

**Comment by marklit** [comment]
Great, thank you.

**Comment by giswqs** [comment]
GitHub Actions failed because it took more than six hours. That's why I have to run it locally. Once it is done, I will push the updates to GitHub tomorrow morning. 

https://github.com/opengeos/maxar-open-data/actions/runs/6836105556
image

**Pull request merged**
